### ISSUE TITLE
Custom Recipe Requests

### ISSUE THREAD

**Issue by RyanP1991** [RyanP1991/TWPI-Custom-Pack---1.12#55]
Please insert here any recipe requests required, including creative items if you guys are interested.

- [x] Binnie's Dyes script from Builder's Paradise
- [x] Flux Sponge
- [x] PSI Creative Suspension
- [x] Creative Mana Pool
- [x] Creative Mana Tablet

**Comment by Hekera** [comment]
- [ ] [Psi creative suspension](https://cdn.discordapp.com/attachments/601234389824700447/602378686343151627/unknown.png) `mods.extendedcrafting.TableCrafting.addShaped(0, <rpsideas:creative_colorizer>, [
    [null, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, <ore:blockInfinity>, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, null], 
    [null, <botania:elfglass>, <ore:ingotInfinity>, <avaritia:resource>, <ore:ingotInfinity>, <botania:elfglass>, null], 
    [null, <botania:elfglass>, <ore:ingotInfinity>, <psi:cadcolorizer:16>, <ore:ingotInfinity>, <botania:elfglass>, null], 
    [null, <botania:elfglass>, <ore:ingotInfinity>, <avaritia:resource:5>, <ore:ingotInfinity>, <botania:elfglass>, null], 
    [null, <botania:elfglass>, <ore:ingotInfinity>, <psi:cadcolorizer:16>, <ore:ingotInfinity>, <botania:elfglass>, null], 
    [null, <botania:elfglass>, <ore:ingotInfinity>, <avaritia:resource>, <ore:ingotInfinity>, <botania:elfglass>, null], 
    [null, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, <ore:blockInfinity>, <ore:blockCosmicNeutronium>, <ore:blockCosmicNeutronium>, null]
]);`

**Comment by RyanP1991** [comment]
Wand of Animation

Flux Sponge

**Comment by RyanP1991** [comment]
Thaumcraft - Ancient Stone / Eldritch Stone

**Comment by Hekera** [comment]
Wait, so are we going to have the Wand of Animation or not? I'm fine either way, as long as you nerf Avaritia recipes if we don't have it.

**Comment by canalpa** [comment]
creative tinker modifier

**Comment by Starr12** [comment]
I want to make the Megatorch easier, use iron instead of gold and diamonds or just 9 torches.

I want to make Immersive engineering's steel scaffolding reward more than 3. maybe 6. just to take the initial costs of IE down a peg.

I think we should focus on creative items using Extended Crafting's singularities instead of using Avaritia at all. Less carrot on a stick and more Metroid-Vania.

I want to add a custom super food item that fills your hunger, saturation and all your nutrients in one go for the price of a couple singularities.

I want you to re-add the vanilla bread recipe, and then tweak the pam's method(that requires dough n such) to simply reward MORE bread.

Find a way to "transmute" the vanilla saplings so that any player can go from oak to birch to spruce to dark oak, n such.

Add crafting recipes for the required "starter" eggs in chickens.(log, bone, sand quartz chickens) Preferably in the Actually Additions Empowerer or something neat like that. it would extra awesome if the recipe output the roost's hatched and item-i-fied chickens instead of a likely empty egg.

Luka suggested disabling Academy Craft's ores and changing the items to use all vanilla, but late game items so that it's ores clutter up the world less.

Add a way to get thermal's last 2 teirs of metals with out having to hunt down mobs all the time. Maybe compact Ice or something.

Environemental Tech will need to be adjusted to drop only the proper ores and resources.

I need to look through inventory pets some more for recipes, that's my one TODO for tommorow.

The ...color? paste used to make dark utils false blocks will probably have to be tweaked to be as fair and as on par as Secret rooms 5.

I personally think the flat colored blocks crafting thing should be easier, like made entirely from wood or something.

In the survey, I had 12 unanimous answers to make chisel and chisel and bits chisels to make those tools pretty much unbreakable. Buidling the I-chisel and the Diamond chisel should yield versions that have like mending 50 on them or something.(I don't know if their durability can be tweaked/removed)

**Comment by Starr12** [comment]
Creative Items:

EU2 Builder's Wand
RFtools Creative Power Cell
Mekanism's Creative Gas Tank(Needs Survey)
Mekanism's Creative Fluid Tank(Needs Survey)
Creative Computer Case
Creative Drone Case
Flux Sponge
Creative Probe can be neat
Thermal's Creative Converion Kit
Thermal's Creative Bore, Saw, and Magnet
Creative Jetpack
Tinker's Creative Modifier
Creative CAD Assembly
Creative Storage Modifier
Creative Vending modifier(Needs survey)
Everlasting Guilty Pool
Creative Railcraft Choochoo
Creative Collar from Doggy Talents
Creative Model Learner(Deep mob learning)
Creative Essence

**Comment by Hekera** [comment]
Creative Mill

**Comment by Jadziyah** [comment]
> * [Done] I want to make the Megatorch easier, use iron instead of gold and diamonds or just 9 torches.
> * [Done] I want to make Immersive engineering's steel scaffolding reward more than 3. maybe 6. just to take the initial costs of IE down a peg.
> * [] I think we should focus on creative items using Extended Crafting's singularities instead of using Avaritia at all. Less carrot on a stick and more Metroid-Vania.
> * [Can't Do] I want to add a custom super food item that fills your hunger, saturation and all your nutrients in one go for the price of a couple singularities.
> * [Done] I want you to re-add the vanilla bread recipe, and then tweak the pam's method(that requires dough n such) to simply reward MORE bread.
> * [Done] Find a way to "transmute" the vanilla saplings so that any player can go from oak to birch to spruce to dark oak, n such.
> * [Done] Add crafting recipes for the required "starter" eggs in chickens.(log, bone, sand. quartz chickens and more) Preferably in the Actually Additions Empowerer or something neat like that. it would extra awesome if the recipe output the roost's hatched and item-i-fied chickens instead of a likely empty egg.
> * [] Luka suggested disabling Academy Craft's ores and changing the items to use all vanilla, but late game items so that it's ores clutter up the world less.
> * [Deep Mob Learning] Add a way to get thermal's last 2 teirs of metals with out having to hunt down mobs all the time. Maybe compact Ice or something.
> * [No need to touch] Environemental Tech will need to be adjusted to drop only the proper ores and resources.
> 
> I need to look through inventory pets some more for recipes, that's my one TODO for tommorow.
> 
> * [Not Needed] The ...color? paste used to make dark utils false blocks will probably have to be tweaked to be as fair and as on par as Secret rooms 5.
> * [Look at me guys I like to make silly comments] I personally think the flat colored blocks crafting thing should be easier, like made entirely from wood or something.
> * [Done] In the survey, I had 12 unanimous answers to make chisel and chisel and bits chisels to make those tools pretty much unbreakable. Buidling the I-chisel and the Diamond chisel should yield versions that have like mending 50 on them or something.(I don't know if their durability can be tweaked/removed)

Okay I guess I'm too late as most of this has already been addressed. But need to say:

> * I personally think the flat colored blocks crafting thing should be easier, like made entirely from wood or something.

There is literally *one* 'tool' to make in that mod, and that's it. Just that. It does *not* need to be nerfed. And this is coming from a builder who actually uses it a lot

> * In the survey, I had 12 unanimous answers to make chisel and chisel and bits chisels to make those tools pretty much unbreakable.

There might have been 12 people saying otherwise but it wasn't unanimous- I personally said no. And again, this is coming from someone who uses those tools a ton. But w/e, this one doesn't really matter that much to me

> * [Done] Add crafting recipes for the required "starter" eggs in chickens.(log, bone, sand. quartz chickens and more) 

...why? This is a really easy mod to begin with. Oh well

> I need to look through inventory pets some more for recipes, that's my one TODO for tommorow.

If this one is still not finished I need to strongly object. The mod is meant to encourage exploration. Yes, it is based on luck. But that adds to the playing experience, and lengthens the playtime as well. Why does *everything* have to be craftable? Those "Omg yay!" moments when you open a chest and see that item you've been searching for are wonderful and part of the Minecraft charm. Again, Inventory Pets is a mod I love (I'm the one that suggested it) but I really believe this should not be dumbed down so much. There aren't that many pets to begin with, it generally doesn't take a player too long to complete their collection. 

We're already chipping away @ exploration by making vanilla saplings switchable. Project E was cut out so this wasn't an instant Easy Mode pack. Let's not make it so by dribs and drabs. 

The rest of the items I am indifferent to or agree with.
